version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: taskflow_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - taskflow_network
    restart: unless-stopped

  app:
    build: .
    container_name: taskflow_app
    environment:
      DB_HOST: prestige-park-groove.cb4e4w6y2od4.us-east-1.rds.amazonaws.com
      DB_USER: postgres
      DB_PASSWORD: your_password_here
      DB_NAME: postgres
      DB_PORT: 5432
      REDIS_HOST: redis
    ports:
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
    networks:
      - taskflow_network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  taskflow_network:
    driver: bridge